version: '2'
services:
  mywildfly:
    image: online-auction:latest
    ports:
      - 9090:8080
  MySQL:
    container_name: "db"
    image: mysql:latest
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=hwr_auction
      - MYSQL_ROOT_PASSWORD=Ioriyagami88